// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jfqvjwolbahxqkhvajwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmcXZqd29sYmFoeHFraHZhandkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NzE1NzYsImV4cCI6MjA5MDQ0NzU3Nn0.wMO8_gouNBaWI-bepEd9BlCfTxDZcnNswiurHZpRpbI";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);